# Load in NumPy (pip numpy first)

In [1]:
import numpy as np

# The Basics

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,2.3,7.0],[5.0,4.0,3.7]])
print(b)

[[9.  2.3 7. ]
 [5.  4.  3.7]]


In [4]:
# Get Dimension
a.ndim

1

In [5]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [6]:
# Get Type
a.dtype

dtype('int32')

In [7]:
# Get Size
a.itemsize

4

In [8]:
# Get total size
print(a.size * a.itemsize)
print(a.nbytes)

12
12


# Accessing/Chaningin specific elements, rows, columns etc.

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Get a specific element [r,c]
a[1,5]
a[1,-2] # also negative, backwards

13

In [11]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get a specific column 
a[:,2]

array([ 3, 10])

In [13]:
# Getting a little mor fancy [startindex:endindex:stepsize]
a[0, 1:6:2]
a[0, 1:-1:2] # fancier

array([2, 4, 6])

In [14]:
# Change a value
a[1,5] = 20
print(a)

a[:,2] = 5
print(a)

a[:,6] = 1,2
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  1]
 [ 8  9  5 11 12 20  2]]


*3D example

In [15]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
# Get specific element (work outside in)
print(b[0,1,1])
print(b[:,1,:])
print(b[:,0,:])

4
[[3 4]
 [7 8]]
[[1 2]
 [5 6]]


In [17]:
# replace
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initialize Different Types of Arrays

In [18]:
# All zeroes matrix
np.zeros((2,3)) # specify the shape

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# All one's matrix (with a specific datatype [voluntary])
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [20]:
# Any other number (with a specific datatype [voluntary])
np.full((2,2), 99, dtype="float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

Array creation routines: https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

In [21]:
# Any other number (full_like) as the same shape as another array
np.full_like(a, 4)
# or
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [22]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.98734813, 0.27600586],
       [0.90175789, 0.98960734],
       [0.21028033, 0.40365984],
       [0.79008175, 0.70359705]])

In [23]:
# in a specific shape
np.random.random_sample(a.shape)

array([[0.78049888, 0.36072525, 0.54767687, 0.903274  , 0.94285936,
        0.54941543, 0.35212063],
       [0.86245289, 0.81339767, 0.84402999, 0.78167287, 0.53078528,
        0.03346097, 0.0368746 ]])

In [24]:
# Random Integer values
# specify start value; no value - starts at zero
#end value is not included (exlusive)
print(np.random.randint(7, size=(3,3)))
print(np.random.randint(1,36, size=(5,7)))

[[6 3 4]
 [0 1 6]
 [6 6 3]]
[[29 12 23 34 15  3  2]
 [12 28  1 18 16  7 26]
 [27 15 11  2 34 26 27]
 [ 7  8  3 15 19 34 22]
 [26 24 27 21 23 18 32]]


In [25]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [37]:
#excersise
#my solution:
array = np.ones((5,5), dtype='int32')
array[1:4,1:4] = np.zeros((3,3), dtype='int32')
array[2,2] = 9
print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Be careful when copying arrays

In [43]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)
#otherwise both get 100 as first element

[100   2   3]
[1 2 3]


# Mathematics

In [44]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [45]:
a + 2

array([3, 4, 5, 6])

In [46]:
a - 2

array([-1,  0,  1,  2])

In [47]:
a * 2

array([2, 4, 6, 8])

In [48]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [50]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [51]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [52]:
# Take the sine
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

More on math: https://docs.scipy.org/doc/numpy/reference/routines.math.html

#### Linear algebra

In [61]:
# Matrix mulitplication
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [60]:
# Find the determinant
c =  np.identity(3)
np.linalg.det(c)

1.0

More linear algebra things: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

#### Statistics

In [63]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:

np.min(stats) #axis=1

array([1, 4])

In [65]:
np.max(stats)

6

In [70]:
np.sum(stats) #axis for columnwise

21

# Reorganizing Arrays

In [77]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

after2 = before.reshape((4,2))
print(after2)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [94]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

[1 2 3 4]


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:
# Horizontal stacks
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(h1) 
print(h2)

np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

### Load Data from File

In [99]:
filedata = np.genfromtxt('data.txt', delimiter=",") # delimiter - how the data is split
#change format from float to int
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Boolean Masking and Advanced indexing

In [100]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [101]:
filedata[filedata > 50] # and others

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [102]:
# You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [103]:
# if we look downwards is any of the data greater than 50
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [104]:
# if we look downwards is any of the data greater than 50, axis = 0 is columns
np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [107]:
print(((filedata > 50) & (filedata < 100)))

print(~((filedata > 50) & (filedata < 100))) # ~ is NOT

[[False False False False False  True False False False False False False
  False False False False False False]
 [False False False False False  True False  True False False False False
  False False False False False False]
 [False False False False False False False False  True False False False
  False False False False  True  True]]
[[ True  True  True  True  True False  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True False  True  True  True
   True  True  True  True False False]]
