# Load in NumPy (pip numpy first)

In [24]:
import numpy as np

# The Basics

In [25]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [26]:
b = np.array([[9.0,2.3,7.0],[5.0,4.0,3.7]])
print(b)

[[9.  2.3 7. ]
 [5.  4.  3.7]]


In [27]:
# Get Dimension
a.ndim

1

In [28]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [29]:
# Get Type
a.dtype

dtype('int32')

In [30]:
# Get Size
a.itemsize

4

In [31]:
# Get total size
print(a.size * a.itemsize)
print(a.nbytes)

12
12


# Accessing/Chaningin specific elements, rows, columns etc.

In [34]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [36]:
# Get a specific element [r,c]
a[1,5]
a[1,-2] # also negative, backwards

13

In [37]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
# Get a specific column 
a[:,2]

array([ 3, 10])

In [40]:
# Getting a little mor fancy [startindex:endindex:stepsize]
a[0, 1:6:2]
a[0, 1:-1:2] # fancier

array([2, 4, 6])

In [46]:
# Change a value
a[1,5] = 20
print(a)

a[:,2] = 5
print(a)

a[:,6] = 1,2
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  1]
 [ 8  9  5 11 12 20  2]]


*3D example

In [50]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [53]:
# Get specific element (work outside in)
print(b[0,1,1])
print(b[:,1,:])
print(b[:,0,:])

4
[[3 4]
 [7 8]]
[[1 2]
 [5 6]]


In [55]:
# replace
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initialize Different Types of Arrays

In [59]:
# All zeroes matrix
np.zeros((2,3)) # specify the shape

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
# All one's matrix (with a specific datatype [voluntary])
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [64]:
# Any other number (with a specific datatype [voluntary])
np.full((2,2), 99, dtype="float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

Array creation routines: https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

In [67]:
# Any other number (full_like) as the same shape as another array
np.full_like(a, 4)
# or
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [68]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.42911637, 0.16272182],
       [0.27254313, 0.8410106 ],
       [0.94626944, 0.12543614],
       [0.30347024, 0.706361  ]])

In [74]:
# in a specific shape
np.random.random_sample(a.shape)

array([[0.51266904, 0.7592422 , 0.95317866, 0.01443532, 0.19724772,
        0.81814625, 0.07140652],
       [0.09789906, 0.71733002, 0.07855548, 0.19466818, 0.77434081,
        0.89553862, 0.15128218]])

In [80]:
# Random Integer values
# specify start value; no value - starts at zero
#end value is not included (exlusive)
print(np.random.randint(7, size=(3,3)))
print(np.random.randint(1,36, size=(5,7)))

[[0 4 0]
 [2 1 6]
 [2 4 0]]
[[ 3 16  7 31  4 18 15]
 [18 21 23  6 18 18  9]
 [20 21 26 18  2 23 26]
 [30 13 23  1 18 32 21]
 [14  3 34 33  1 33 35]]


In [82]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [89]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
